-- Bang cac nhan vien
create table employees
(
    id              integer primary key generated by default as identity,
    first_name      varchar(255) not null,
    last_name       varchar(255) not null,
    email           varchar(255) not null,
    salary          money        not null check (salary > 0::money),
    profile_picture text         not null,
    is_manager      boolean      not null default false,
    password        varchar(255) not null
);

-- Bang cac nha cung cap
create table providers
(
    id      integer primary key generated by default as identity,
    name    varchar(255) not null,
    address varchar(255) not null
);

-- Cac vat pham
create table items
(
    id          integer primary key generated by default as identity,
    name        varchar(255) not null,
    image       text         not null,
    quantity    integer      not null check (quantity > 0),
    description text,
    provider_id integer references providers (id) on delete cascade
);

create table customers
(
    id           integer primary key generated by default as identity,
    first_name   varchar(255) not null,
    last_name    varchar(255) not null,
    phone_number varchar(20)  not null,
    email        varchar(255) not null
);

-- Hoa don
create table invoices
(
    id          integer primary key generated by default as identity,
    total       money                               not null check (total > 0::money),
    employee_id integer                             not null references employees (id) on delete cascade,
    customer_id integer                             not null references customers (id) on delete cascade,
    created_at  timestamp default current_timestamp not null
);

-- Danh sach cac vat pham trong hoa don
create table invoices_items
(
    invoice_id integer not null references invoices (id) on delete cascade,
    item_id    integer not null references items (id) on delete cascade,
    quantity   integer not null check (quantity > 0),
    primary key (invoice_id, item_id)
);

create table tags
(
    id          integer primary key generated by default as identity,
    name        varchar(255) not null,
    description text
);

create table items_tags
(
    item_id integer references items (id) on delete cascade,
    tag_id  integer references tags (id) on delete cascade,
    primary key (item_id, tag_id)
);

create table price_types
(
    id   integer primary key generated by default as identity,
    name varchar(255) not null
);

create table item_prices
(
    id         integer primary key generated by default as identity,
    item_id    integer not null references items (id) on delete cascade,
    price_type integer not null references price_types (id) on delete cascade,
    divider    integer not null check (divider > 0),
    value      integer not null check (value > 0),
    begin_date date    not null,
    end_date   date    not null
);

create table imports
(
    id          integer primary key generated by default as identity,
    provider_id integer                             not null references providers (id) on delete cascade,
    created_at  timestamp default current_timestamp not null
);

create table import_items
(
    import_id integer not null references imports (id) on delete cascade,
    item_id   integer not null references items (id) on delete cascade,
    quantity  integer not null check (quantity > 0),
    primary key (import_id, item_id)
);
