-- Bang cac nhan vien
create table employees
(
    employee_id     integer primary key generated by default as identity,
    -- Ho va ten dem
    first_name      varchar(255) not null,
    -- Ten
    last_name       varchar(255) not null,
    -- Email
    email           varchar(255) not null,
    -- luong
    salary          money        not null check (salary > 0::money),
    profile_picture bytea        not null,
    -- Co phai quan ly khong
    is_manager      boolean      not null default false,
    deleted         boolean      not null default false
);

-- Bang cac nha cung cap
create table providers
(
    provider_id integer primary key generated by default as identity,
    -- Ten
    name        varchar(255) not null,
    -- Dia chi
    address     varchar(255) not null,
    deleted     boolean not null default false
);

-- Cac vat pham
create table items
(
    item_id     integer primary key generated by default as identity,
    name        varchar(255) not null,
    image       bytea        not null,
    -- So luong
    quantity    integer      not null check (quantity > 0),
    -- Thong tin chi tiet
    description text,                 -- text la nvarchar khong co gioi han do dai
    price       money        not null, -- Don gia
    provider_id integer references providers(provider_id),
    deleted     boolean not null default false
);

create table providers_items
(
    item_id     integer references items(item_id),
    provider_id integer references  providers(provider_id),
    primary key (item_id, provider_id)
);

-- Hoa don
create table invoices
(
    invoice_id  integer primary key generated by default as identity,
    -- Tong tri gia hoa don
    total       money                               not null check (total > 0::money),
    -- Nhan vien xu ly hoa don
    employee_id integer                             not null references employees (employee_id),
    -- Thoi gian lap hoa don (khong can chen nua, thoi gian nay duoc tu dong chen)
    created_at  timestamp default current_timestamp not null,
    deleted     boolean not null default false
);

-- Danh sach cac vat pham trong hoa don
create table invoices_items
(
    invoice_id integer references invoices (invoice_id) not null,
    item_id    integer references items (item_id)       not null,
    quantity   integer                                  not null check (quantity > 0),
    primary key (invoice_id, item_id)
);

create table tags
(
    name        varchar(255) primary key not null,
    description text,
    deleted     boolean not null default false
);

create table items_tags
(
    item_id  integer references items (item_id),
    tag_name varchar(255) references tags (name),
    primary key (item_id, tag_name)
);
